/*=============================================================================
    PROYECTO: SISTEMA DE GESTIÓN Y CONTROL DE ASISTENCIA DEL COMEDOR UNIVERSITARIO
    ESPECIFICACIÓN: Creación de tablas y datos semilla optimizados para Supabase.
    AUTOR: Antigravity AI Coding Assistant
    SGBD: PostgreSQL (Supabase BaaS)
    ACTUALIZACIÓN: Autenticación por DNI + contraseña | 5 roles | módulo Postulante público
=============================================================================*/

-- 1. LIMPIEZA DE TABLAS EXISTENTES (Orden descendente de dependencias)
DROP TABLE IF EXISTS public.reporte CASCADE;
DROP TABLE IF EXISTS public.asistencia CASCADE;
DROP TABLE IF EXISTS public.detalle_solicitud CASCADE;
DROP TABLE IF EXISTS public.solicitud CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.personal CASCADE;
DROP TABLE IF EXISTS public.beneficiario CASCADE;
DROP TABLE IF EXISTS public.postulacion CASCADE;
DROP TABLE IF EXISTS public.estudiante CASCADE;
DROP TABLE IF EXISTS public.escuela_profesional CASCADE;
DROP TABLE IF EXISTS public.estado_solicitud CASCADE;
DROP TABLE IF EXISTS public.estado_postulacion CASCADE;
DROP TABLE IF EXISTS public.horario CASCADE;
DROP TABLE IF EXISTS public.tipo_racion CASCADE;
DROP TABLE IF EXISTS public.facultad CASCADE;
DROP TABLE IF EXISTS public.cargo CASCADE;
DROP TABLE IF EXISTS public.rol CASCADE;
DROP TABLE IF EXISTS public.estado CASCADE;

/*=============================================================================
    PARTE 1: TABLAS MAESTRAS (NIVEL 1)
=============================================================================*/

-- 1.1 TABLA ESTADO (General)
CREATE TABLE public.estado (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado VARCHAR(30) NOT NULL UNIQUE
);

-- 1.2 TABLA ROL (5 roles del sistema)
-- 1=Administrador, 2=Dirección de Bienestar, 3=Asistente Social, 4=Beneficiario, 5=Postulante
CREATE TABLE public.rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE
);

-- 1.3 TABLA FACULTAD
CREATE TABLE public.facultad (
    id_facultad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_facultad VARCHAR(120) NOT NULL UNIQUE
);

-- 1.4 TABLA TIPO RACION
CREATE TABLE public.tipo_racion (
    id_tipo_racion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_racion VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(150),
    costo DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

-- 1.5 TABLA HORARIO
CREATE TABLE public.horario (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_horario VARCHAR(40) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL
);

-- 1.6 TABLA CARGO (Cargos del personal de la UNAM)
CREATE TABLE public.cargo (
    id_cargo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cargo VARCHAR(80) NOT NULL UNIQUE
);

-- 1.7 TABLA ESTADO POSTULACION (Fase de Admisión)
CREATE TABLE public.estado_postulacion (
    id_estado_postulacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado VARCHAR(30) NOT NULL UNIQUE
);

-- 1.8 TABLA ESTADO SOLICITUD (Reservas de comida)
CREATE TABLE public.estado_solicitud (
    id_estado_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado VARCHAR(30) NOT NULL UNIQUE
);


/*=============================================================================
    PARTE 2: TABLAS CON DEPENDENCIAS SIMPLES (NIVEL 2)
=============================================================================*/

-- 2.1 TABLA ESCUELA PROFESIONAL (Depende de Facultad)
CREATE TABLE public.escuela_profesional (
    id_escuela INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_escuela VARCHAR(120) NOT NULL UNIQUE,
    id_facultad INTEGER NOT NULL,
    CONSTRAINT fk_escuela_facultad FOREIGN KEY (id_facultad) REFERENCES public.facultad(id_facultad) ON DELETE RESTRICT
);

-- 2.2 TABLA ESTUDIANTE (Base común para Postulantes y Beneficiarios)
CREATE TABLE public.estudiante (
    id_estudiante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_universitario VARCHAR(12) NOT NULL UNIQUE,
    dni CHAR(8) NOT NULL UNIQUE,
    nombres VARCHAR(80) NOT NULL,
    apellidos VARCHAR(80) NOT NULL,
    sexo CHAR(1) CHECK (sexo IN ('M', 'F')),
    fecha_nacimiento DATE,
    telefono VARCHAR(15),
    correo VARCHAR(100),
    direccion VARCHAR(150),
    ciclo SMALLINT CHECK (ciclo BETWEEN 1 AND 14),
    id_escuela INTEGER NOT NULL,
    id_estado INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_estudiante_escuela FOREIGN KEY (id_escuela) REFERENCES public.escuela_profesional(id_escuela) ON DELETE RESTRICT,
    CONSTRAINT fk_estudiante_estado FOREIGN KEY (id_estado) REFERENCES public.estado(id_estado) ON DELETE RESTRICT
);

-- 2.3 TABLA POSTULACION
-- La columna 'observacion' sirve como comentario de admisión/rechazo redactado por DBU.
CREATE TABLE public.postulacion (
    id_postulacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante INTEGER NOT NULL,
    fecha_postulacion DATE NOT NULL DEFAULT CURRENT_DATE,
    observacion VARCHAR(300),        -- Comentario de admisión / razón de rechazo (escrito por DBU)
    documentos_completos BOOLEAN DEFAULT FALSE,
    entrevista_realizada BOOLEAN DEFAULT FALSE,
    id_estado_postulacion INTEGER NOT NULL DEFAULT 1,
    url_fut VARCHAR(255) NULL,                     -- URL del documento FUT en Supabase Storage
    url_ficha_socioeconomica VARCHAR(255) NULL,    -- URL de la ficha socioeconómica
    url_constancia_matricula VARCHAR(255) NULL,    -- URL de la constancia de matrícula
    CONSTRAINT fk_postulacion_estudiante FOREIGN KEY (id_estudiante) REFERENCES public.estudiante(id_estudiante) ON DELETE CASCADE,
    CONSTRAINT fk_postulacion_estado_postulacion FOREIGN KEY (id_estado_postulacion) REFERENCES public.estado_postulacion(id_estado_postulacion) ON DELETE RESTRICT
);


/*=============================================================================
    PARTE 3: GESTIÓN DE BENEFICIARIOS Y PERSONAL (NIVEL 3)
=============================================================================*/

-- 3.1 TABLA BENEFICIARIO (Estudiantes admitidos al comedor)
CREATE TABLE public.beneficiario (
    id_beneficiario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion INTEGER NOT NULL UNIQUE,
    fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin DATE,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_beneficiario_postulacion FOREIGN KEY (id_postulacion) REFERENCES public.postulacion(id_postulacion) ON DELETE RESTRICT
);

-- 3.2 TABLA PERSONAL (Dirección de Bienestar, Asistentes Sociales y Soporte Técnico)
CREATE TABLE public.personal (
    id_personal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(80) NOT NULL,
    apellidos VARCHAR(80) NOT NULL,
    numero_documento VARCHAR(15) NOT NULL UNIQUE,
    telefono VARCHAR(15),
    correo VARCHAR(100),
    direccion VARCHAR(150),
    id_cargo INTEGER NOT NULL,
    id_estado INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_personal_cargo FOREIGN KEY (id_cargo) REFERENCES public.cargo(id_cargo) ON DELETE RESTRICT,
    CONSTRAINT fk_personal_estado FOREIGN KEY (id_estado) REFERENCES public.estado(id_estado) ON DELETE RESTRICT
);

-- 3.3 TABLA USUARIO
-- AUTENTICACIÓN: DNI + contraseña (no username/código).
-- El campo id_usuario mapea al UUID de auth.users de Supabase.
-- Para estudiantes (roles 4 y 5): el login usa el DNI de la tabla estudiante.
-- Para personal (roles 1, 2, 3): el login usa el numero_documento de la tabla personal.
CREATE TABLE public.usuario (
    id_usuario UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contrasena VARCHAR(200) NOT NULL,              -- Contraseña definida por el usuario o generada por el sistema
    id_rol INTEGER NOT NULL,
    id_estudiante INTEGER NULL UNIQUE,             -- Solo para roles 4 (Beneficiario) y 5 (Postulante)
    id_personal INTEGER NULL UNIQUE,               -- Solo para roles 1 (Admin), 2 (DBU) y 3 (Asistente Social)
    id_beneficiario INTEGER NULL UNIQUE,           -- Se asigna cuando pasa de Postulante (5) a Beneficiario (4)
    id_estado INTEGER NOT NULL DEFAULT 1,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_estudiante FOREIGN KEY (id_estudiante) REFERENCES public.estudiante(id_estudiante) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_personal FOREIGN KEY (id_personal) REFERENCES public.personal(id_personal) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_beneficiario FOREIGN KEY (id_beneficiario) REFERENCES public.beneficiario(id_beneficiario) ON DELETE SET NULL,
    CONSTRAINT fk_usuario_estado FOREIGN KEY (id_estado) REFERENCES public.estado(id_estado) ON DELETE RESTRICT,

    -- Roles de Alumnos (4=Beneficiario, 5=Postulante): deben tener id_estudiante y no id_personal
    -- Roles de Personal (1=Admin, 2=DBU, 3=Asistente Social): deben tener id_personal y no id_estudiante
    CONSTRAINT ck_usuario_rol_asociacion CHECK (
        (id_rol IN (4, 5) AND id_estudiante IS NOT NULL AND id_personal IS NULL) OR
        (id_rol IN (1, 2, 3) AND id_personal IS NOT NULL AND id_estudiante IS NULL)
    )
);


/*=============================================================================
    PARTE 4: GESTIÓN DE RESERVAS Y CONTROL DE ASISTENCIA (NIVEL 4)
=============================================================================*/

-- 4.1 TABLA SOLICITUD (Reservas diarias de alimentación de beneficiarios)
CREATE TABLE public.solicitud (
    id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_solicitud DATE NOT NULL DEFAULT CURRENT_DATE,
    id_beneficiario INTEGER NOT NULL,
    id_tipo_racion INTEGER NOT NULL,
    id_horario INTEGER NOT NULL,
    id_estado_solicitud INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_solicitud_beneficiario FOREIGN KEY (id_beneficiario) REFERENCES public.beneficiario(id_beneficiario) ON DELETE CASCADE,
    CONSTRAINT fk_solicitud_tipo_racion FOREIGN KEY (id_tipo_racion) REFERENCES public.tipo_racion(id_tipo_racion) ON DELETE RESTRICT,
    CONSTRAINT fk_solicitud_horario FOREIGN KEY (id_horario) REFERENCES public.horario(id_horario) ON DELETE RESTRICT,
    CONSTRAINT fk_solicitud_estado_solicitud FOREIGN KEY (id_estado_solicitud) REFERENCES public.estado_solicitud(id_estado_solicitud) ON DELETE RESTRICT
);

-- 4.2 TABLA DETALLE SOLICITUD
CREATE TABLE public.detalle_solicitud (
    id_detalle_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud INTEGER NOT NULL,
    observacion VARCHAR(250),
    fecha_atencion TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_detalle_solicitud_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud(id_solicitud) ON DELETE CASCADE
);

-- 4.3 TABLA ASISTENCIA (Control transaccional diario)
CREATE TABLE public.asistencia (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud INTEGER NOT NULL,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    hora TIME NOT NULL DEFAULT CURRENT_TIME,
    asistio BOOLEAN NOT NULL DEFAULT FALSE,
    justificado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_asistencia_solicitud FOREIGN KEY (id_solicitud) REFERENCES public.solicitud(id_solicitud) ON DELETE CASCADE
);


/*=============================================================================
    PARTE 5: REPORTES (NIVEL 4)
=============================================================================*/

-- 5.1 TABLA REPORTE (Historial administrativo)
CREATE TABLE public.reporte (
    id_reporte INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_reporte VARCHAR(100) NOT NULL,
    fecha_generacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    descripcion VARCHAR(250),
    id_personal INTEGER NOT NULL,
    CONSTRAINT fk_reporte_personal FOREIGN KEY (id_personal) REFERENCES public.personal(id_personal) ON DELETE CASCADE
);


/*=============================================================================
    PARTE 6: INSERCIÓN DE DATOS SEMILLA (CATÁLOGOS)
=============================================================================*/

-- 6.1 ESTADOS
INSERT INTO public.estado (nombre_estado) VALUES
('Activo'),
('Inactivo'),
('Suspendido');

-- 6.2 ROLES (5 módulos del sistema)
-- IMPORTANTE: El orden de inserción define el ID secuencial.
INSERT INTO public.rol (nombre_rol) VALUES
('Administrador'),                          -- ID 1: Técnico/Ingeniero de Sistemas
('Dirección de Bienestar Universitario'),   -- ID 2: Evaluación y aprobación de becas
('Asistente Social'),                       -- ID 3: Control de asistencias y FUT
('Beneficiario'),                           -- ID 4: Alumnos con beca alimentaria activa
('Postulante');                             -- ID 5: Alumnos en proceso de selección (sin login fijo)

-- 6.3 FACULTADES (UNAM - Moquegua)
INSERT INTO public.facultad (nombre_facultad) VALUES
('Facultad de Ingeniería'),
('Facultad de Ciencias Jurídicas y Empresariales'),
('Facultad de Ciencias de la Salud');

-- 6.4 ESCUELAS PROFESIONALES (UNAM - Filial Ilo y Moquegua)
INSERT INTO public.escuela_profesional (nombre_escuela, id_facultad) VALUES
('Escuela Profesional de Ingeniería de Sistemas e Informática', 1),
('Escuela Profesional de Ingeniería de Minas', 1),
('Escuela Profesional de Ingeniería Ambiental', 1),
('Escuela Profesional de Derecho y Ciencias Políticas', 2),
('Escuela Profesional de Gestión Pública y Desarrollo Social', 2),
('Escuela Profesional de Medicina Humana', 3);

-- 6.5 TIPOS DE RACION
INSERT INTO public.tipo_racion (nombre_racion, descripcion, costo) VALUES
('Desayuno', 'Ración de desayuno básico estudiantil', 0.00),
('Almuerzo', 'Almuerzo completo (entrada, segundo, bebida)', 0.00);

-- 6.6 HORARIOS DE SERVICIO
INSERT INTO public.horario (nombre_horario, hora_inicio, hora_fin) VALUES
('Servicio de Desayuno', '07:00:00', '09:00:00'),
('Servicio de Almuerzo', '11:45:00', '14:30:00');

-- 6.7 CARGOS DEL PERSONAL
INSERT INTO public.cargo (nombre_cargo) VALUES
('Director de Bienestar Universitario'),
('Asistente Social Principal'),
('Ingeniero de Soporte y Sistemas'),
('Registrador de Comedor');

-- 6.8 ESTADOS DE POSTULACIÓN
INSERT INTO public.estado_postulacion (nombre_estado) VALUES
('Pendiente'),           -- 1: Recibida, en espera de revisión
('En Evaluación'),       -- 2: DBU está revisando el expediente
('Aprobado'),            -- 3: Admitido como beneficiario
('Rechazado'),           -- 4: No cumplió los requisitos (con comentario de DBU)
('En Lista de Espera');  -- 5: Aprobado pero sin vacante disponible aún

-- 6.9 ESTADOS DE LA SOLICITUD DE RACIÓN
INSERT INTO public.estado_solicitud (nombre_estado) VALUES
('Reservado'),
('Atendido'),
('No Asistido'),
('Cancelado');
